name: QMK build

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: QMK userspace build
    permissions:
      contents: write
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@ae0d588378c528a97635c7dc4345fff2a2ff5dac
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master
